Japanese translation of the settings page has been added.
test-zawa/Prompt-Engineering-Guide pull request #1
Opened 2024-01-17 01:43 UTC by test-zawa

2024-01-17 01:44 UTC, iwashi commented on pages/introduction/settings.jp.mdx
> +**Max Length** - この値を調整することで、モデルが生成するトークンの数を管理することができます。長すぎるまたは関連性のない回答を防ぎ、コストを抑えることができます。
この値を調整することで -> この値の調整により

2024-01-24 16:00 UTC, iwashi requested changes
@test-zawa 
いくつかコメントしてみましたので、こちらをご確認ください。

2024-01-24 16:00 UTC, iwashi commented on pages/introduction/settings.jp.mdx
> +**Max Length** - この値を調整することで、モデルが生成するトークンの数を管理することができます。長すぎるまたは関連性のない回答を防ぎ、コストを抑えることができます。
11行目に対するコメントではないのですが、 9行目を消しておかないと、19行目と重複になります。

2024-01-24 16:00 UTC, iwashi commented on pages/introduction/settings.jp.mdx
> +**Max Length** - この値を調整することで、モデルが生成するトークンの数を管理することができます。長すぎるまたは関連性のない回答を防ぎ、コストを抑えることができます。
```suggestion
**Max Length** - この値の調整により、モデルが生成するトークンの数を管理できます。長すぎるまたは関連性のない回答を防ぎ、コストを管理できます。
```

で、いかがでしょうか？

2024-01-24 16:00 UTC, iwashi commented on pages/introduction/settings.jp.mdx
> +**Stop Sequences** - Stop Sequencesは、モデルがトークンを生成するのを停止する文字列です。これを指定することは、モデルの回答の長さや構造を制御するもう一つの方法です。例えば、"11"をストップシーケンスとして追加することで、モデルに10項目以上のリストを生成させないように指示することができます。
```suggestion
**Stop Sequences** - Stop Sequencesは、モデルがトークンを生成するのを停止する文字列です。これを指定することは、モデルの回答の長さや構造を制御するもう一つの方法です。例えば、"11"をストップシーケンスとして追加により、モデルに10項目以上のリストを生成させないように指示できます。
```

〜すること　というのが続くと、くどい日本語になりがちなのでちょっとシンプルにしてはいかがでしょうか？

2024-01-24 16:00 UTC, iwashi commented on pages/introduction/settings.jp.mdx
> +**Presence Penalty** - Presence Penaltyも頻繁に繰り返されるトークンに対するペナルティを適用しますが、Frequency Penaltyとは異なり、すべての繰り返されるトークンに対して同じペナルティが適用されます。2回現れるトークンも10回現れるトークンも同じペナルティが課されます。この設定は、モデルが頻繁に同じフレーズを繰り返すのを防ぎます。もしモデルに多
> Or, if you need the model to stay focused, try using a lower presence penalty.

最後の文が訳抜けのようです。

2024-01-29 21:34 UTC, iwashi commented
@test-zawa 修正終わりましたら、 @iwashi までメンションください！

2024-01-30 03:45 UTC, test-zawa commented
修正遅くなり申し訳ありません！
本日中に修正します！

2024-01-30 03:47 UTC, test-zawa commented
@iwashi 
修正遅くなり申し訳ありません！
本日中に修正したものをプッシュします！

2024-01-31 23:03 UTC, test-zawa commented
@iwashi 
遅くなり申し訳ありません。
頂いたコメントを元に修正しました。

特に、最後の翻訳抜けの部分について、
「if you need the model to stay focused」
　→ 「モデルが生成するテキストを特定のフレーズに集中させたい場合は」
としましたが、適切な解釈か自信がありませんので、ご確認お願いします

2024-02-01 04:07 UTC, iwashi commented on pages/introduction/settings.jp.mdx
> +**Presence Penalty** - Presence Penaltyも頻繁に繰り返されるトークンに対するペナルティを適用しますが、Frequency Penaltyとは異なり、すべての繰り返されるトークンに対して同じペナルティが適用されます。2回現れるトークンも10回現れるトークンも同じペナルティが課されます。この設定は、モデルが頻繁に同じフレーズを繰り返すのを防ぎます。もしモデルに多
```suggestion
**Presence Penalty** - Presence Penaltyも頻繁に繰り返されるトークンに対するペナルティを適用しますが、Frequency Penaltyとは異なり、すべての繰り返されるトークンに対して同じペナルティが適用されます。2回現れるトークンも10回現れるトークンも同じペナルティが課されます。この設定は、モデルが頻繁に同じフレーズを繰り返すのを防ぎます。もしモデルに多様性のある、あるいは創造的なテキストを生成させたい場合は、この値を高めに設定すると良いでしょう。モデルが生成するテキストを特定のフレーズに集中させたい場合は、低めに設定してみてください。
```

**Presence Penalty** - Presence Penaltyも頻繁に繰り返されるトークンに対するペナルティを適用しますが、Frequency Penaltyとは異なり、すべての繰り返されるトークンに対して同じペナルティが適用されます。2回現れるトークンも10回現れるトークンも同じペナルティが課されます。この設定は、モデルが頻繁に同じフレーズを繰り返すのを防ぎます。もしモデルに多様性のある、あるいは創造的なテキストを生成させたい場合は、この値を高めに設定すると良いでしょう。モデルが生成するテキストが特定のフレーズに集中しても良い場合は、低めに設定してみてください。

2024-02-14 06:30 UTC, test-zawa commented
@iwashi 
頂いたコメントをもとに修正しました。
なお、ブランチをきれいにする方法については、手順の確認まで実施し、
実際の作業は未実施です

2024-02-14 06:56 UTC, merged